auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: Vivian's Blog”
title: Vivian's blog
description: Everything about Mukosame.
url: http://vivian0316.github.io
feed: /atom.xml
author_info: <a href="http://vivian0316.github.io/">Home</a>
